Repository bigbio/quantms.io, pull requests merged in 2025-09, with the labels that each got.

#109 Fix the quantms LFQ/TMT modules
  quantmsio/commands/convert/quantms.py
  quantmsio/core/duckdb.py
  quantmsio/core/quantms/feature.py
  quantmsio/core/quantms/mztab.py
  quantmsio/core/quantms/pg.py
  quantmsio/core/quantms/psm.py
  quantmsio/utils/constants.py
  tests/core/quantms/psms/test_duckdb_creation.py
  tests/core/quantms/psms/test_mztab_indexer.py
  tests/core/quantms/psms/test_psm.py
  tests/core/quantms/test_feature.py
  tests/core/quantms/test_full_conversion_suite.py
  tests/core/quantms/test_msstats_in.py
  tests/core/test_large_mztab_performance.py
Labels: Review effort 4/5

#114 fix: improve quantms convert
  quantmsio/core/quantms/feature.py
  quantmsio/core/quantms/mztab.py
  quantmsio/core/quantms/pg.py
  quantmsio/operate/tools.py
  quantmsio/quantmsioc.py
Labels: Review effort 3/5

#117 Optimize some files based on CodeFactor.
  quantmsio/commands/convert/quantms.py
  quantmsio/core/idxml.py
  quantmsio/core/openms.py
  quantmsio/core/quantms/feature.py
  quantmsio/core/quantms/mztab.py
  quantmsio/core/quantms/psm.py
  quantmsio/utils/mztab_utils.py
  tests/core/idxml/test_idxml_psm.py
  tests/core/quantms/psms/test_duckdb_creation.py
  tests/core/quantms/psms/test_psm.py
  tests/core/quantms/test_feature.py
  tests/core/quantms/test_msstats_in.py
  tests/core/test_large_mztab_performance.py
Labels: Review effort 4/5

#118 Add optional spectral data fields
  docs/README.adoc
  quantmsio/commands/convert/idxml.py
  quantmsio/commands/convert/maxquant.py
  quantmsio/commands/convert/quantms.py
  quantmsio/core/format.py
  quantmsio/core/idxml.py
  quantmsio/core/idxml_utils/idxml.py
  quantmsio/core/maxquant/maxquant.py
  quantmsio/core/quantms/psm.py
  quantmsio/quantmsioc.py
Labels: Review effort 3/5

#119 Merge main into dev.
  quantmsio/core/fragpipe/fragpipe.py
  quantmsio/operate/tools.py
  tests/test_fragment_annotations.py
Labels: Review effort 2/5
